# Generated by Django 2.0.6 on 2018-06-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add the new kernel field to the hosts model. It's nullable for now, before the migration is completed."""

    dependencies = [
        ('hosts', '0001_initial'),
        ('kernels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='kernel',
            field=models.ForeignKey(
                help_text='Running kernel.', on_delete=models.deletion.PROTECT, related_name='hosts',
                to='kernels.KernelVersion', verbose_name='running kernel', null=True),
        ),
    ]
