# Generated by Django 2.0.6 on 2018-06-21 06:12

from django.db import migrations


def forwards_func(apps, schema_editor):
    """For each host add the reference to its KernelVersion object, creating it if not existing."""
    Host = apps.get_model('hosts', 'Host')
    KernelVersion = apps.get_model('kernels', 'KernelVersion')

    for item in Host.objects.select_related(None):
        kernel, _ = KernelVersion.objects.get_or_create(
            name=item.running_kernel, slug=item.running_kernel_slug, os=item.os)
        item.kernel = kernel
        item.save()


def reverse_func(apps, schema_editor):
    """For each host add the data from its KernelVersion object back to the hosts table."""
    Host = apps.get_model('hosts', 'Host')

    for item in Host.objects.select_related('kernel'):
        item.running_kernel = item.kernel.name
        item.running_kernel_slug = item.kernel.slug
        item.save()


class Migration(migrations.Migration):
    """Data migration to move the Kernel data between the hosts table and the kernels one."""

    dependencies = [
        ('hosts', '0002_auto_20180621_0609'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
