# Generated by Django 2.1.15 on 2020-01-14 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0005_auto_20180621_0620'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='hostpackage',
            index=models.Index(fields=['upgrade_type', 'upgradable_package'], name='hosts_hostp_upgrade_3aa6f3_idx'),
        ),
    ]
