# Generated by Django 3.2.25 on 2025-06-25 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0002_auto_20200114_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='KubernetesImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.CharField(help_text='Kubernetes cluster name.', max_length=255)),
                ('namespace', models.CharField(help_text='Kubernetes cluster namespace name.', max_length=255)),
                ('instances', models.PositiveIntegerField(help_text='How many running instances of this image.')),
                ('created',
                 models.DateTimeField(auto_now_add=True, help_text='Datetime of the creation of this object.')),
                ('modified',
                 models.DateTimeField(auto_now=True, help_text='Datetime of the last modification of this object.')),
                ('image', models.ForeignKey(
                    help_text='Container image deployed in this Kubernetes cluster and namespace.',
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='instances', to='images.image', verbose_name='container image')),
            ],
            options={
                'verbose_name': 'kubernetes',
                'verbose_name_plural': 'kubernetes',
                'ordering': ['cluster', 'namespace', 'image'],
                'unique_together': {('cluster', 'namespace', 'image')},
            },
        ),
    ]
