# Generated by Django 3.2.25 on 2025-07-02 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20200114_1132'),
        ('kubernetes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kubernetesimage',
            old_name='instances',
            new_name='containers',
        ),
        migrations.AlterField(
            model_name='kubernetesimage',
            name='containers',
            field=models.PositiveIntegerField(
                help_text='How many running containers in this cluster and namespace this image has.'
            ),
        ),
        migrations.AlterField(
            model_name='kubernetesimage',
            name='image',
            field=models.ForeignKey(
                help_text='Container image deployed in this Kubernetes cluster and namespace.',
                on_delete=django.db.models.deletion.PROTECT,
                related_name='namespaces',
                to='images.image',
                verbose_name='image',
            ),
        ),
    ]
