# flake8: noqa: E501
# Skip flake test for overly long lines, auto-generated file
# Generated by Django 2.1.10 on 2019-12-06 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bin_packages', '0001_initial'),
        ('src_packages', '0002_auto_20180410_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Container image name', max_length=255, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Datetime of the creation of this object.')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Datetime of the last modification of this object.')),
                ('os', models.ForeignKey(help_text='Operating system.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='src_packages.OS', verbose_name='operating system')),
            ],
            options={
                'verbose_name_plural': 'images',
                'ordering': ['name'],
                'verbose_name': 'image',
            },
        ),
        migrations.CreateModel(
            name='ImagePackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upgrade_type', models.CharField(blank=True, help_text='Upgrade type (security)', max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Datetime of the creation of this object.')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Datetime of the last modification of this object.')),
                ('image', models.ForeignKey(help_text='Container image package name', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='images.Image')),
                ('package', models.ForeignKey(help_text='Binary package.', on_delete=django.db.models.deletion.PROTECT, related_name='installed_images', to='bin_packages.Package', verbose_name='binary package')),
                ('package_version', models.ForeignKey(help_text='Binary package version.', on_delete=django.db.models.deletion.PROTECT, related_name='installed_images', to='bin_packages.PackageVersion', verbose_name='binary package version')),
                ('upgradable_imagepackage', models.ForeignKey(blank=True, help_text='Upgradable binary package.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='upgradable_images', to='bin_packages.Package', verbose_name='upgradable binary package')),
                ('upgradable_imageversion', models.ForeignKey(blank=True, help_text='Upgradable binary package version.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='upgradable_images', to='bin_packages.PackageVersion', verbose_name='upgradable binary package version')),
            ],
            options={
                'verbose_name_plural': 'image packages',
                'ordering': ['image__name', 'package__name', 'package_version__version'],
                'verbose_name': 'image package',
            },
        ),
        migrations.AddField(
            model_name='image',
            name='package_versions',
            field=models.ManyToManyField(blank=True, db_index=True, help_text='Binary package versions installed in this container image', related_name='_image_package_versions_+', through='images.ImagePackage', to='bin_packages.PackageVersion', verbose_name='binary package versions'),
        ),
        migrations.AddField(
            model_name='image',
            name='packages',
            field=models.ManyToManyField(blank=True, db_index=True, help_text='Binary packages installed in this container image', related_name='_image_packages_+', through='images.ImagePackage', to='bin_packages.Package', verbose_name='binary packages'),
        ),
        migrations.AddField(
            model_name='image',
            name='upgradable_imagepackages',
            field=models.ManyToManyField(blank=True, db_index=True, help_text='Binary packages installed on this image that could be upgraded.', related_name='_image_upgradable_imagepackages_+', through='images.ImagePackage', to='bin_packages.Package', verbose_name='upgradable binary packages'),
        ),
        migrations.AddField(
            model_name='image',
            name='upgradable_versions',
            field=models.ManyToManyField(blank=True, db_index=True, help_text='Binary package versions installed on this image that could be upgraded.', related_name='_image_upgradable_versions_+', through='images.ImagePackage', to='bin_packages.PackageVersion', verbose_name='upgradable binary package versions'),
        ),
        migrations.AlterUniqueTogether(
            name='imagepackage',
            unique_together={('image', 'package')},
        ),
    ]
