# Generated by Django 2.0.6 on 2018-06-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    """Remove nullability from the kernel field, after the data migration was completed."""

    dependencies = [
        ('hosts', '0003_auto_20180621_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='kernel',
            field=models.ForeignKey(
                help_text='Running kernel.', on_delete=models.deletion.PROTECT, related_name='hosts',
                to='kernels.KernelVersion', verbose_name='running kernel'),
        ),
    ]
