# Generated by Django 2.0.6 on 2018-06-21 06:20

from django.db import migrations


class Migration(migrations.Migration):
    """Remove the not anymore used running_kernel fields in the host model."""

    dependencies = [
        ('hosts', '0004_auto_20180621_0617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='running_kernel',
        ),
        migrations.RemoveField(
            model_name='host',
            name='running_kernel_slug',
        ),
    ]
