# Generated by Django 2.0.6 on 2018-06-21 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('src_packages', '0002_auto_20180410_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='KernelVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Kernel version.', max_length=255)),
                ('slug', models.SlugField(help_text='Kernel version and OS URL slug.', max_length=255)),
                ('created', models.DateTimeField(
                    auto_now_add=True, help_text='Datetime of the creation of this object.')),
                ('modified', models.DateTimeField(
                    auto_now=True, help_text='Datetime of the last modification of this object.')),
                ('os', models.ForeignKey(
                    help_text='Operating system.', on_delete=django.db.models.deletion.PROTECT, related_name='+',
                    to='src_packages.OS', verbose_name='operating system')),
            ],
            options={
                'verbose_name': 'kernel',
                'verbose_name_plural': 'kernels',
                'ordering': ['os__name', 'name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='kernelversion',
            unique_together={('name', 'os')},
        ),
    ]
