# Generated by Django 2.0.4 on 2018-04-10 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Operating system name.', max_length=32, unique=True)),
            ],
            options={
                'verbose_name': 'operating system',
                'verbose_name_plural': 'operating systems',
            },
        ),
        migrations.CreateModel(
            name='SrcPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Source package name.', max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'source package',
                'verbose_name_plural': 'source packages',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SrcPackageVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Version.', max_length=255)),
                ('created', models.DateTimeField(
                    auto_now_add=True, help_text='Datetime of the creation of this object.')),
                ('modified', models.DateTimeField(
                    auto_now=True, help_text='Datetime of the last modification of this object.')),
                ('os', models.ForeignKey(
                    db_index=False, help_text='Operating system.', on_delete=django.db.models.deletion.PROTECT,
                    related_name='+', to='src_packages.OS')),
                ('src_package', models.ForeignKey(
                    db_index=False, help_text='Source package.', on_delete=django.db.models.deletion.PROTECT,
                    related_name='versions', to='src_packages.SrcPackage', verbose_name='source package')),
            ],
            options={
                'verbose_name': 'source package version',
                'verbose_name_plural': 'source package versions',
                'ordering': ['src_package__name', 'os__name', 'version'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='srcpackageversion',
            unique_together={('src_package', 'version', 'os')},
        ),
    ]
