# Generated by Django 2.0.4 on 2018-04-10 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('src_packages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Binary package name.', max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'package',
                'verbose_name_plural': 'packages',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PackageVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Binary package version.', max_length=255)),
                ('created', models.DateTimeField(
                    auto_now_add=True, help_text='Datetime of the creation of this object.')),
                ('modified', models.DateTimeField(
                    auto_now=True, help_text='Datetime of the last modification of this object.')),
                ('os', models.ForeignKey(
                    db_index=False, help_text='Operating system.', on_delete=django.db.models.deletion.PROTECT,
                    related_name='+', to='src_packages.OS', verbose_name='operating system')),
                ('package', models.ForeignKey(
                    db_index=False, help_text='Binary package.', on_delete=django.db.models.deletion.PROTECT,
                    related_name='versions', to='bin_packages.Package')),
                ('src_package_version', models.ForeignKey(
                    help_text='Source package version that generated this binary package version.',
                    on_delete=django.db.models.deletion.PROTECT, related_name='binaries',
                    to='src_packages.SrcPackageVersion', verbose_name='source package version')),
            ],
            options={
                'verbose_name': 'package version',
                'verbose_name_plural': 'package versions',
                'ordering': ['package__name', 'version'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='packageversion',
            unique_together={('package', 'version', 'os')},
        ),
    ]
