# Generated by Django 2.0.4 on 2018-04-10 21:34

from django.db import migrations


def add_os(apps, schema_editor):
    """Add the OSes to the DB."""
    os = apps.get_model('src_packages', 'OS')
    for os_name in ('Debian', 'Ubuntu'):
        os(name=os_name).save()


class Migration(migrations.Migration):
    """Data migration to import OSes."""

    dependencies = [
        ('src_packages', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_os),
    ]
