# Generated by Django 3.2.25 on 2025-06-24 10:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src_packages', '0002_auto_20180410_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='os',
            name='name',
            field=models.CharField(
                help_text='Operating system name.',
                max_length=32,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message=('The OS name needs to follow the following pattern: '
                                 '^(Debian( \\d\\d)?|Ubuntu( \\d\\d\\.\\d\\d)?)$'),
                        regex='^(Debian( \\d\\d)?|Ubuntu( \\d\\d\\.\\d\\d)?)$')]),
        ),
    ]
